final List<String> breedList = [
  'Dalmata',
  'Mestizo',
  'Malix',
  'Schnauzer',
  'Pitbull',
  'Border Collie',
  'Poodle',
  'Labrador Retriever',
  'Chihuahua',
  'Pug',
  'Salchicha',
  'Gran Danés',
  'Husky Siberiano',
  'Rottweiler',
  'Beagle',
  'Golden Retriever',
  'Husky',
  'Cocker Spaniel',
  'Bulldog',
  'Pastor Alemán',
  'Boxer',
  'Basset Hound',
  'Doberman',
  'Shih Tzu',
  'Bull Terrier',
  'Yorkshire Terrier',
  'Maltés',
  'Boston Terrier',
  'Akita Inu',
  'Samoyedo',
  'Chow Chow',
  'Jack Russell Terrier',
  'Australian Shepherd',
  'Pomerania'
];
