final List<Map<String, List<String>>> breedList = [
  {
    'perro': [
      'Dalmata',
      'Mestizo',
      'Malix',
      'Schnauzer',
      'Pitbull',
      'Border Collie',
      'Poodle',
      'Labrador Retriever',
      'Chihuahua',
      'Pug',
      'Salchicha',
      'Gran Danés',
      'Rottweiler',
      'Beagle',
      'Golden Retriever',
      'Husky',
      'Cocker Spaniel',
      'Bulldog',
      'Pastor Alemán',
      'Boxer',
      'Basset Hound',
      'Doberman',
      'Shih Tzu',
      'Bull Terrier',
      'Yorkshire Terrier',
      'Maltés',
      'Boston Terrier',
      'Akita Inu',
      'Samoyedo',
      'Chow Chow',
      'Jack Russell Terrier',
      'Australian Shepherd',
      'Pomerania'
    ],
  },
  {
    'gato': [
      'Persa',
      'Siamés',
      'Maine Coon',
      'Bengalí',
      'Ragdoll',
      'Abisinio',
      'Sphynx',
      'Británico de pelo corto',
      'Devon Rex',
      'Himalayo',
      'Exótico de pelo corto',
      'Manx',
      'Turco Van',
      'Abyssinian',
      'Norwegian Forest Cat',
      'Scottish Fold',
      'Oriental',
      'Birmano',
      'Cornish Rex',
      'Toyger'
    ],
  },
];
